### ISSUE TITLE
Errors resolving assets after upgrade to 4.2.1 from 3.6.0

### ISSUE THREAD

**Issue by nstuyvesant** [webpack-contrib/css-loader#1159]
- Operating System: macOS 10.15.6
- Node Version: 14.7.0
- NPM Version: 6.14.7
- webpack Version: 4.44.1
- css-loader Version: 4.2.1

### Expected Behavior

Same behavior using 3.6.0.

### Actual Behavior

```
ERROR in ./client/app/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '/assets/fonts/glyphicons-halflings-regular.eot' in '/Users/nates/dev/shy/client/app'
    at /Users/nates/dev/shy/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /Users/nates/dev/shy/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/nates/dev/shy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/nates/dev/shy/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /Users/nates/dev/shy/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/nates/dev/shy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/nates/dev/shy/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/nates/dev/shy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/nates/dev/shy/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /Users/nates/dev/shy/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at /Users/nates/dev/shy/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/nates/dev/shy/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/nates/dev/shy/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/nates/dev/shy/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/nates/dev/shy/node_modules/css-loader/dist/index.js:152:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./client/app/app.module.js 70:0-20
```

### Code

```js
// webpack.config.js module.rules array element

        {
          test: /\.(sa|sc|c)ss$/,
          include: [
            path.resolve(__dirname, 'client/app/app.scss')
          ],
          use: [
            MiniCssExtractPlugin.loader,
            {
              loader: 'css-loader',
            },
            {
              loader: 'postcss-loader',
              options: {
                plugins: () => [autoprefixer()]
              }
            },
            {
              loader: 'sass-loader',
            }
          ]
        }
```

### How Do We Reproduce?

$ git clone https://github.com/nstuyvesant/shy.git
$ cd shy
change version of css-loader in package.json to 4.2.1 then...
$ npm install
$ gulp build

**Comment by evilebottnawi** [comment]
Please use search before post the issue and read the error, we can't resolve `/assets/fonts/glyphicons-halflings-regular.eot` because you don't have the file
