### ISSUE TITLE
Exception if url contains percent symbol

### ISSUE THREAD

**Issue by xarety** [webpack-contrib/css-loader#1287]
- Operating System: macOS 11.2.3
- Node Version: 14.15.2
- NPM Version: 6.14.9
- webpack Version: 4.46.0
- css-loader Version: 5.2.0

Seems like [this](https://github.com/webpack-contrib/css-loader/pull/1277) changeset brokes [this line](https://github.com/webpack-contrib/css-loader/blob/v5.2.0/src/plugins/postcss-url-parser.js#L130).

### Expected Behavior

Webpack bundling finish successfully.

### Actual Behavior

```
ERROR in ./src/index.css
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
URIError: URI malformed
    at /Users/xarety/servicetitan/url-bug-reproduction/src/index.css:2:5
    at decodeURI (<anonymous>)
    at normalizeUrl (/Users/xarety/servicetitan/url-bug-reproduction/node_modules/css-loader/dist/utils.js:114:10)
    at /Users/xarety/servicetitan/url-bug-reproduction/node_modules/css-loader/dist/plugins/postcss-url-parser.js:119:37
    at walk (/Users/xarety/servicetitan/url-bug-reproduction/node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (/Users/xarety/servicetitan/url-bug-reproduction/node_modules/postcss-value-parser/lib/index.js:18:3)
    at parseDeclaration (/Users/xarety/servicetitan/url-bug-reproduction/node_modules/css-loader/dist/plugins/postcss-url-parser.js:97:10)
    at Declaration (/Users/xarety/servicetitan/url-bug-reproduction/node_modules/css-loader/dist/plugins/postcss-url-parser.js:248:29)
    at LazyResult.visitTick (/Users/xarety/servicetitan/url-bug-reproduction/node_modules/postcss/lib/lazy-result.js:456:16)
    at LazyResult.runAsync (/Users/xarety/servicetitan/url-bug-reproduction/node_modules/postcss/lib/lazy-result.js:372:30)
    at LazyResult.async (/Users/xarety/servicetitan/url-bug-reproduction/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (/Users/xarety/servicetitan/url-bug-reproduction/node_modules/postcss/lib/lazy-result.js:190:17)
 @ ./src/index.js 1:0-22
```

### Code

https://github.com/xarety/url-bug-reproduction

### How Do We Reproduce?

1. clone [repository](https://github.com/xarety/url-bug-reproduction)
2. `npm i`
3. `npm run build`

**Comment by alexander-akait** [comment]
hm, svg should be encoded here, I can add `try/catch`

**Comment by xarety** [comment]
Otherwise, it should have a meaningful error message at least. 🙂

**Comment by alexander-akait** [comment]
Anyway we should ignore this,I will fix it

**Comment by xarety** [comment]
Thank you!

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/css-loader/releases/tag/v5.2.1
