### ISSUE TITLE
Cannot find module indexes-of

### ISSUE THREAD

**Issue by vvasuki** [webpack-contrib/css-loader#1296]
- Operating System: Arch Linux
- Node Version: v10.24.0
- NPM Version: 7.11.1
- webpack Version: 5.36.0
- css-loader Version: 5.2.4

### Error
```
ERROR in ./node_modules/tachyons/css/tachyons.min.css (./node_modules/css-loader/dist/cjs.js!./node_modules/tachyons/css/tachyons.min.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Cannot find module 'indexes-of'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/vvasuki/vvasuki-git/saMskAra/themes/sanskrit-documentation-theme-hugo/webpack_src/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/vvasuki/vvasuki-git/saMskAra/themes/sanskrit-documentation-theme-hugo/webpack_src/node_modules/postcss-selector-parser/dist/parser.js:6:41)
    at Module._compile (/home/vvasuki/vvasuki-git/saMskAra/themes/sanskrit-documentation-theme-hugo/webpack_src/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
 @ ./node_modules/tachyons/css/tachyons.min.css 2:12-84 9:17-24 13:15-29
 @ ./js/ui-lib.js 3:0-39

webpack 5.36.0 compiled with 5 errors in 2984 ms
[build] [nodemon] app crashed - waiting for file changes before starting...

```

**Comment by alexander-akait** [comment]
Please remove `node_modules` and install again, you have broken `node_modules`, `indexes-of` was removed in `postcss-selector-parser`
