### ISSUE TITLE
modules.mode = 'icss' should validate

### ISSUE THREAD

**Issue by ntucker** [webpack-contrib/css-loader#1341]
`modules: {
                mode: 'icss',
              },` is valid by the release notes as well as the readme docs

- Operating System:
- Node Version:16
- NPM Version:7
- webpack Version:5
- css-loader Version:6

### Expected Behavior

It works

### Actual Behavior

```
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.modules should be one of these:
   boolean | "local" | "global" | "pure" | object { compileType?, auto?, mode?, localIdentName?, localIdentContext?, localIdentHashPrefix?, localIdentRegExp?, getLocalIdent?, namedExport?, exportGlobals?, exportLocalsConvention?, exportOnlyLocals? }
   -> Enables/Disables CSS Modules and their configuration (https://github.com/webpack-contrib/css-loader#modules).
   Details:
    * options.modules.mode should be one of these:
      "local" | "global" | "pure" | function
      -> Setup `mode` option (https://github.com/webpack-contrib/css-loader#mode).
      Details:
       * options.modules.mode should be one of these:
         "local" | "global" | "pure"
       * options.modules.mode should be an instance of function.
    at validate (/home/ntucker/src/anansi/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.loader (/home/ntucker/src/anansi/node_modules/css-loader/dist/index.js:36:29)
    at processResult (/home/ntucker/src/anansi/node_modules/webpack/lib/NormalModule.js:701:19)
    at /home/ntucker/src/anansi/node_modules/webpack/lib/NormalModule.js:807:5
    at /home/ntucker/src/anansi/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/ntucker/src/anansi/node_modules/loader-runner/lib/LoaderRunner.js:251:18

```

### Code

```js
{
loader: require.resolve('css-loader')
options: {
              importLoaders: 1,
              modules: {
                mode: 'icss',
              },
            }
}
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by ntucker** [comment]
This was a mistake on my part - my yarn resolutions accidentally didn't let me actually upgrade.
