### ISSUE TITLE
[BUG] css-loader.js > processCss function, will cause `Cant resolve module 'xxxx'` in some case

### ISSUE THREAD

**Issue by inxi-pc** [webpack-contrib/css-loader#338]
This is code snippets

``` javascript
// css-loader.js > processCss
        if(query.url !== false) {
            cssAsString = cssAsString.replace(result.urlItemRegExpG, function(item) {
                var match = result.urlItemRegExp.exec(item);
                var idx = +match[1];
                var urlItem = result.urlItems[idx];
                var url = urlItem.url;
                idx = url.indexOf("?#");
                if(idx < 0) idx = url.indexOf("#");
                var urlRequest;
                if(idx > 0) { // idx === 0 is catched by isUrlRequest
                    // in cases like url('webfont.eot?#iefix')
                    urlRequest = url.substr(0, idx);
                    return "\" + require(" + loaderUtils.stringifyRequest(this, urlRequest) + ") + \"" +
                            url.substr(idx);
                }
                urlRequest = url;
                return "\" + require(" + loaderUtils.stringifyRequest(this, urlRequest) + ") + \"";
            }.bind(this));
        }
```

In my application, i use some external library, like bootstrap, tinymce(a js editor), work on 

modules mode, `"css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]"` 

but i always met

a error `Cant resolve module 'xxxx'` when i complier the application, the error occur in css 

url('path') function. We know the url path has two type, relative path and absolute path. The

issue case is in relative path. In css library, the relative has two type writing method, one is 

`'test/test.gif'`, the other is `'./test/test.gif'`, the former is the simplify way, it is equal the latter. 

But when css-loader process the `'test/test.gif'`, it cause issue `Cant resolve module 'xxxx'`.

Below is my console.log in processCss funciton, and get processed url list.

``` javascript
xiongbingchao@xiongbingchaodeiMac ~/D/my-blog-admin>
webpack --progress --display-modules --display-chunks -v
 65% 75/81 build modules
../fonts/glyphicons-halflings-regular.eot
../fonts/glyphicons-halflings-regular.eot?#iefix
../fonts/glyphicons-halflings-regular.woff2
../fonts/glyphicons-halflings-regular.woff
../fonts/glyphicons-halflings-regular.ttf
../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
 67% 78/81 build modules
img/loader.gif
fonts/tinymce.eot
fonts/tinymce.eot?#iefix
fonts/tinymce.woff
fonts/tinymce.ttf
fonts/tinymce.svg#tinymce
fonts/tinymce-small.eot
fonts/tinymce-small.eot?#iefix
fonts/tinymce-small.woff
fonts/tinymce-small.ttf
fonts/tinymce-small.svg#tinymce
 68% 79/81 build modules
img/object.gif
img/anchor.gif
 67% 107/112 build modules
../fonts/glyphicons-halflings-regular.eot
../fonts/glyphicons-halflings-regular.eot?#iefix
../fonts/glyphicons-halflings-regular.woff2
../fonts/glyphicons-halflings-regular.woff
../fonts/glyphicons-halflings-regular.ttf
../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
img/loader.gif
fonts/tinymce.eot
fonts/tinymce.eot?#iefix
fonts/tinymce.woff
fonts/tinymce.ttf
fonts/tinymce.svg#tinymce
fonts/tinymce-small.eot
fonts/tinymce-small.eot?#iefix
fonts/tinymce-small.woff
fonts/tinymce-small.ttf
fonts/tinymce-small.svg#tinymce
img/object.gif
img/anchor.gif
```

and the error (hide some):

``` javascript
ERROR in ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/skin.min.css
Module not found: Error: Cannot resolve module 'img/loader.gif' in /Users/xiongbingchao/Developer/my-blog-admin/node_modules/tinymce/skins/lightgray
 @ ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/skin.min.css 6:38076-38101

ERROR in ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/content.min.css
Module not found: Error: Cannot resolve module 'img/object.gif' in /Users/xiongbingchao/Developer/my-blog-admin/node_modules/tinymce/skins/lightgray
 @ ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/content.min.css 6:1050-1075

ERROR in ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/skin.min.css
Module not found: Error: Cannot resolve module 'fonts/tinymce.eot' in /Users/xiongbingchao/Developer/my-blog-admin/node_modules/tinymce/skins/lightgray
 @ ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/skin.min.css 6:42791-42819 6:42837-42865

ERROR in ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/skin.min.css
Module not found: Error: Cannot resolve module 'fonts/tinymce.woff' in /Users/xiongbingchao/Developer/my-blog-admin/node_modules/tinymce/skins/lightgray
 @ ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/skin.min.css 6:42914-42943

ERROR in ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/skin.min.css
Module not found: Error: Cannot resolve module 'fonts/tinymce.ttf' in /Users/xiongbingchao/Developer/my-blog-admin/node_modules/tinymce/skins/lightgray
 @ ./~/css-loader?modules&localIdentName=[name]__[local]___[hash:base64:5]!./~/tinymce/skins/lightgray/skin.min.css 6:42972-43000
```

All error occur in 'directory/xxxx', but the relative path './dictory/xxxx' or '../../dictory/xxx' has

no issue any more. 

I guess, the former path module finding way is not same as the latter, the latter will get module 

base on the relative path, they can find the module, but the former will not. So i change the code,

to process this type path, it is simple, only add the './' before the path. Now, the application 

complier normally :)

this is my change:

``` javascript

cssAsString = cssAsString.replace(result.importItemRegExpG, importItemMatcher.bind(this));
        if(query.url !== false) {
            cssAsString = cssAsString.replace(result.urlItemRegExpG, function(item) {
                var match = result.urlItemRegExp.exec(item);
                var idx = +match[1];
                var urlItem = result.urlItems[idx];
                var url = urlItem.url;
                // add first letter reg, if true add prefix
                var preReg = /^\w/;
                if (preReg.test(url)) {
                    url = './' + url;
                }
                idx = url.indexOf("?#");
                if(idx < 0) idx = url.indexOf("#");
                var urlRequest;
                if(idx > 0) { // idx === 0 is catched by isUrlRequest
                    // in cases like url('webfont.eot?#iefix')
                    urlRequest = url.substr(0, idx);
                    return "\" + require(" + loaderUtils.stringifyRequest(this, urlRequest) + ") + \"" +
                            url.substr(idx);
                }
                urlRequest = url;
                return "\" + require(" + loaderUtils.stringifyRequest(this, urlRequest) + ") + \"";
            }.bind(this));
        }

```

i will push a pull request, pls check this sitation. Thanks!

**Comment by michael-ciniawsky** [comment]
Discussion moved to PR #339

**Comment by kopax** [comment]
I have the same issue when trying to build in webpack tinymyce : 


```

ERROR in ./node_modules/tinymce/skins/lightgray/img/loader.gif
Module build failed: Error: spawn /usr/src/app/node_modules/gifsicle/vendor/gifsicle ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/css-loader!./node_modules/tinymce/skins/lightgray/skin.min.css 6:32349-32376
 @ ./node_modules/tinymce/skins/lightgray/skin.min.css
```

How did you guys solve it ?
