### ISSUE TITLE
Error with `import`ed CSS and sourceMap active

### ISSUE THREAD

**Issue by BrainCrumbz** [webpack-contrib/css-loader#360]
### Scenario
1. Angular 2, webpack 2, typescript 2 web application served by node and express.js
2. Build chain has both development build as well as production one (with Angular AOT compile and uglifyjs)
3. A _global_ CSS file is imported in an Angular top-level file, **not** as a component style URL, but as an app-wide style.
4. Global CSS is imported by `import`, not by `require()`, as the latter is not compatible when building with AOT
5. Global CSS is picked up by webpack _module\loaders_ rule: `loaders: ['style-loader', 'css-loader?sourceMap', 'postcss-loader?sourceMap'],`

My team angular 2 [starter project](https://github.com/BrainCrumbz/YANGTSE) shows the issue at this branch created on purpose for it: [issue/css-loader-sourcemap](https://github.com/BrainCrumbz/YANGTSE/tree/issue/css-loader-sourcemap).
- Mentioned loader rule is [here](https://github.com/BrainCrumbz/YANGTSE/blob/c7aeb265618336430108b61bb403a1e619fe2edf/webpack.common.js#L171)
- CSS file is imported from [here](https://github.com/BrainCrumbz/YANGTSE/blob/c7aeb265618336430108b61bb403a1e619fe2edf/src/client/app/app.module.ts#L17)
- Builds can be run with `npm run build-dev` and `npm run build-prod`
### Actual behaviour

Development build fails with error:

> ERROR in D:/myproj/\~/css-loader?sourceMap!D:/myproj/~/postcss-loader?sourceMap!./shared/common-styles.css
> Module build failed: TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.relative (path.js:536:5)
>     at Object.&lt;anonymous&gt; (D:\myproj\node_modules\css-loader\lib\loader.js:101:19)
>     at Array.map (native)
>     at Object.&lt;anonymous&gt; (D:\myproj\node_modules\css-loader\lib\loader.js:99:31)
>     at D:\myproj\node_modules\css-loader\lib\processCss.js:200:3
>     ... stacktrace goes on through core-js

When removing _sourceMap_ option from _css-loader_, build goes fine.
### Expected behaviour

Build should run fine even with sourceMaps active.
### Version
- css-loader: 0.25.0
  - webpack: 2.1.0-beta.25
  - style-loader: 0.13.1
  - sass-loader: 4.0.2
### Environment
- OS: Windows 10
- node: 6.2.2
- npm: 3.9.5
### Debug

Tried adding some console logging to `css-loader\lib\loader.js` around [this bit of code](https://github.com/webpack/css-loader/blob/v0.25.0/lib/loader.js#L101):

``` js
map.sources = map.sources.map(function(source) {
  source = source.split("!").pop();
  // ### custom console logs were added here ###
  var p = path.relative(query.context || this.options.context, source).replace(/\\/g, "/");
  if(p.indexOf("../") !== 0)
    p = "./" + p;
  return "/" + p;
}, this);
```

and for some reason both `query.context` and `this.options.context` are _undefined_

**Comment by orizens** [comment]
i had the same issue.
I found out that the LoaderOptionsPlugin "options" defined in my "webpack.dev.js"  was the "this.options"
https://github.com/wbuchwalter/tslint-loader

**Comment by michael-ciniawsky** [comment]
@BrainCrumbz Could you try without `include` set please?

**Comment by BrainCrumbz** [comment]
Hi there. In the meantime, the actual project we were working at (not the starter one linked above) has obviously evolved. It has webpack 2.2.1, loaders became rules, etc. css-loader is still 0.25.0, style-loader still 0.13.1, sass-loader still 4.0.2. The issue persists, even commenting out *include* set:

```json
// ...
globalCss: {
  test: /^(?!.*component).*\.css$/,
  use: [
    {
      loader: 'style-loader',
    }, {
      loader: 'css-loader',
      options: {
        sourceMap: true,
      },
    }, {
      loader: 'postcss-loader',
      options: {
        sourceMap: true,
      },
    },
  ],
  /*
  include: [
    paths.clientSrc,  // our own client source code
    paths.nodeModules, // allow to import CSS from third-party libraries
  ],
  */
  exclude: [
    paths.buildOutput, // skip output
    paths.codegen, // skip (AOT) generated code
  ],
},
```

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Comment by BrainCrumbz** [comment]
We're on angular-cli at the moment, so not directly accessing webpack options that much these days. Cheers
