### ISSUE TITLE
Importing a .min.css file returns `Module build failed: Error: "/stdin" is not in the SourceMap.`

### ISSUE THREAD

**Issue by okbel** [webpack-contrib/css-loader#374]
Importing a .min.css file returns the following error: `Module build failed: Error: "/stdin" is not in the SourceMap.`

```javascript

ERROR in ./~/css-loader?localIdentName=[path][name]---[local]---[hash:base64:5]!./~/postcss-loader!./~/material-design-lite/material.min.css
Module build failed: Error: "/stdin" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/belencurcio/Develop/talk/node_modules/source-map/lib/source-map-consumer.js:704:13)
    at SourceMapGenerator.<anonymous> (/Users/belencurcio/Develop/talk/node_modules/source-map/lib/source-map-generator.js:235:40)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/belencurcio/Develop/talk/node_modules/source-map/lib/source-map-generator.js:234:32)
    at MapGenerator.applyPrevMaps (/Users/belencurcio/Develop/talk/node_modules/postcss/lib/map-generator.js:146:22)
    at MapGenerator.generateMap (/Users/belencurcio/Develop/talk/node_modules/postcss/lib/map-generator.js:194:46)
    at MapGenerator.generate (/Users/belencurcio/Develop/talk/node_modules/postcss/lib/map-generator.js:297:25)
    at LazyResult.stringify (/Users/belencurcio/Develop/talk/node_modules/postcss/lib/lazy-result.js:296:24)
    at /Users/belencurcio/Develop/talk/node_modules/postcss/lib/lazy-result.js:233:27
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./~/material-design-lite/material.min.css 4:14-155

```

Any solution for this?
Thanks!

**Comment by layanto** [comment]
Same error here

**Comment by joshSummerhays** [comment]
same error here as well, anyone find anything out?

**Comment by ChadElias** [comment]
I am seeing this error as well. However, I am not getting any errors when I switch to the unminified version.

**Comment by RinatMullayanov** [comment]
I have same problem. Is there a solution?

**Comment by michael-ciniawsky** [comment]
@RinatMullayanov Material Design [Lite] aswell ? :)

**Comment by RinatMullayanov** [comment]
@michael-ciniawsky Yes

```shell
ERROR in ./~/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[local]___[hash:base64:8]"}!./~/postcss-loader?{}!./~/material-design-lite/material.min.css
    Module build failed: Error: "/stdin" is not in the SourceMap.
```

**Comment by michael-ciniawsky** [comment]
kk, This happens also when using the non minified version of Material Lite ? Without `postcss-loader`?

**Comment by michael-ciniawsky** [comment]
CSS Modules disabled ?

**Comment by RinatMullayanov** [comment]
@michael-ciniawsky Did not try non minified version of Material Design Lite.
There are two big strange:
1. According to the settings, styles of third-party libraries should not be processed by postcss-loader, only the styles of my application.
2. I have this problem, but my colleague does not have the same code, OS versions, node.js and npm are the same.

**Comment by RinatMullayanov** [comment]
@michael-ciniawsky 
The error appeared as something accidental.
By the way recently we switched to webpack 2, if exactly 2.3.2 version.
With webpack 1, there was no such problem with the same source code.

**Comment by michael-ciniawsky** [comment]
@RinatMullayanov For regression in webpack v2 Core you need to open an issue @webpack/webpack I can't help you here 😛 . So you removed `postcss-loader`and it works? That could likely be the cause, since it will try to generate a new sourcemap, which is undesired in your case

**Comment by evilebottnawi** [comment]
@RinatMullayanov maybe related to `postcss`, wip

**Comment by evilebottnawi** [comment]
Not related to `css-loader`, also seems abandoned issue. Feel free to feedback.
