### ISSUE TITLE
webpack-dev-server: Module build failed: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by aanno** [webpack-contrib/css-loader#435]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**
I'm using ExtractTextPluginTyped to split out css for production. The relevant part of my webpack (2.2.1) config is:

```javascript
            {
              test: /\.(sass|scss)$/i,
              include: path.join(__dirname, "/../src"),
              use: cssExtract.extract({
                use: [
                  {
                    loader: "css-loader",
                    options: {
                      // TODO (tp): I cannot turn on source map generation becasue of
                      // Module build failed: TypeError: Path must be a string. Received undefined
                      sourceMap: false,
                      minimize: args.env === "dist" ? true : false,
                    },
                  },
                  {
                    loader: "sass-loader",
                    options: {
                      sourceMap: false,
                      outputStyle: args.env === "dist" ? "compressed" : "expanded",
                      indentedSyntax: args.env === "dist" ? false : true,
                    },
                  },
                ],
                fallbackLoader: "style-loader",
              }),
            },
```

**If the current behavior is a bug, please provide the steps to reproduce.**
This configuration works for production/bundling. However, when I use it for webpack-dev-server *and enable source maps* the following error occurs:

```
ERROR in ./src/styles/Application.scss
Module build failed: ModuleBuildError: Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1226:5)
    at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:101:19)
    at Array.map (native)
    at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:99:31)
    at /home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/processCss.js:201:3
    at /home/tpasch/scm/wroomer/nextcar/node_modules/webpack/lib/NormalModule.js:141:35
    at /home/tpasch/scm/wroomer/nextcar/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/tpasch/scm/wroomer/nextcar/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/tpasch/scm/wroomer/nextcar/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:32:18)
    at /home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/processCss.js:224:4
 @ ./src/run.tsx 16:0-36
 @ multi webpack-dev-server/client?http://localhost:8000 webpack/hot/dev-server react-hot-loader/patch ./src/run.tsx

ERROR in ./src/styles/Application.scss
Module build failed: ModuleBuildError: Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1226:5)
    at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:101:19)
    at Array.map (native)
    at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:99:31)
    at /home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/processCss.js:201:3
    at /home/tpasch/scm/wroomer/nextcar/node_modules/webpack/lib/NormalModule.js:141:35
    at /home/tpasch/scm/wroomer/nextcar/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/tpasch/scm/wroomer/nextcar/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/tpasch/scm/wroomer/nextcar/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:32:18)
    at /home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/processCss.js:224:4

ERROR in /home/tpasch/scm/wroomer/nextcar/node_modules/extract-text-webpack-plugin/loader.js??ref--4-0!/home/tpasch/scm/wroomer/nextcar/node_modules/style-loader/index.js!/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/index.js??ref--4-2!/home/tpasch/scm/wroomer/nextcar/node_modules/sass-loader/lib/loader.js??ref--4-3!/home/tpasch/scm/wroomer/nextcar/src/styles/Application.scss doesn't export content
Child extract-text-webpack-plugin:
    
    ERROR in ./~/css-loader?{"sourceMap":true,"minimize":false}!./~/sass-loader/lib/loader.js?{"includePaths":["/home/tpasch/scm/wroomer/nextcar/src"],"sourceMap":false,"outputStyle":"expanded","indentedSyntax":true}!./src/styles/Application.scss
    Module build failed: TypeError: Path must be a string. Received undefined
        at assertPath (path.js:7:11)
        at Object.relative (path.js:1226:5)
        at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:101:19)
        at Array.map (native)
        at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:99:31)
        at /home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/processCss.js:201:3
Child extract-text-webpack-plugin:
    
    ERROR in ./~/css-loader?{"sourceMap":true,"minimize":false}!./~/sass-loader/lib/loader.js?{"includePaths":["/home/tpasch/scm/wroomer/nextcar/src"],"sourceMap":false,"outputStyle":"expanded","indentedSyntax":true}!./src/styles/Application.scss
    Module build failed: TypeError: Path must be a string. Received undefined
        at assertPath (path.js:7:11)
        at Object.relative (path.js:1226:5)
        at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:101:19)
        at Array.map (native)
        at Object.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/loader.js:99:31)
        at /home/tpasch/scm/wroomer/nextcar/node_modules/css-loader/lib/processCss.js:201:3
webpack: Failed to compile.
```

**What is the expected behavior?**
No error. The config should work with source map enable even if webpack-dev-server is used.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webpack: 2.2.1
webpack-dev-server: 2.4.1
css-loader: 0.26.2
node: 6.10.0
npm: 3.10.10

**Comment by bebraw** [comment]
Can you set up a standalone example?

**Comment by michael-ciniawsky** [comment]
Reopen anytime if still regressions and a small test repo is provided
