### ISSUE TITLE
Similar Issue like #250 with some differences 

### ISSUE THREAD

**Issue by chandan7193** [webpack-contrib/css-loader#525]
```
Module build failed: Error: Unexpected "space" found.
    at new error (/home/somefolder/anotherfolder/node_modules/postcss-selector-parser/dist/processor.js:29:23)
    at Parser.error (/home/somefolder/anotherfolder/node_modules/postcss-selector-parser/dist/parser.js:234:15)
    at Parser.pseudo (/home/somefolder/anotherfolder/node_modules/postcss-selector-parser/dist/parser.js:362:18)
    at Parser.parse (/home/somefolder/anotherfolder/node_modules/postcss-selector-parser/dist/parser.js:551:22)
    at Parser.loop (/home/somefolder/anotherfolder/node_modules/postcss-selector-parser/dist/parser.js:519:18)
    at new Parser (/home/somefolder/anotherfolder/node_modules/postcss-selector-parser/dist/parser.js:104:21)
    at Processor.process (/home/somefolder/anotherfolder/node_modules/postcss-selector-parser/dist/processor.js:26:21)
    at getParsed (/home/somefolder/anotherfolder/node_modules/postcss-minify-selectors/dist/index.js:32:59)
    at optimise (/home/somefolder/anotherfolder/node_modules/postcss-minify-selectors/dist/index.js:139:21)
    at /home/somefolder/anotherfolder/node_modules/postcss/lib/container.js:241:28
    at /home/somefolder/anotherfolder/node_modules/postcss/lib/container.js:148:26
    at AtRule.each (/home/somefolder/anotherfolder/node_modules/postcss/lib/container.js:114:22)
    at AtRule.walk (/home/somefolder/anotherfolder/node_modules/postcss/lib/container.js:147:21)
    at /home/somefolder/anotherfolder/node_modules/postcss/lib/container.js:150:32
    at Root.each (/home/somefolder/anotherfolder/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/home/somefolder/anotherfolder/node_modules/postcss/lib/container.js:147:21)

error Command failed with exit code 1.
```

**Comment by evilebottnawi** [comment]
@chandan7193 can you create minimal reproducible repo or show your config and files where your get an error?

**Comment by michael-ciniawsky** [comment]
Please also add \``` around the code
