### ISSUE TITLE
Error: File not included into executable

### ISSUE THREAD

**Issue by affanshahid** [webpack-contrib/css-loader#631]
Using `figlet` in my app, throws the following error on running the compiled exe:

```bash
Error: File 'D:\**\ginit\node_modules\figlet\fonts\Standard.flf' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:405:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:629:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:672:18)
    at Function.figlet.loadFontSync (D:\snapshot\ginit\node_modules\figlet\lib\node-figlet.js:38:23)
    at Function.me.textSync (D:\snapshot\ginit\node_modules\figlet\lib\figlet.js:732:43)
    at Object.<anonymous> (D:\snapshot\ginit\test.js:3:20)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

I can't seem to figure out which blob pattern would make this work.

The following example should be enough to trigger this:

```javascript
const figlet = require('figlet');

console.log(figlet.textSync('Hello World!'));
```

**Comment by michael-ciniawsky** [comment]
Wrong repo ? ¯\_(ツ)_/¯ 

The `figlet` module seems trying to read a file

> at Object.**fs.readFileSync** (pkg/prelude/bootstrap.js:672:18)

does `textSync` accept a `{String}` ? 
Maybe it needs a `filepath` instead ? 

Anyways please consider consulting their docs :D

**Comment by affanshahid** [comment]
Completely wrong repo, apologies! Must not have been paying attention when I wrote this.
