### ISSUE TITLE
URL Parsing of CSS Images triggering maximum call stack size exceeded

### ISSUE THREAD

**Issue by Kamadake** [webpack-contrib/css-loader#758]
**Do you want to request a *feature* or report a *bug*?**
Report a bug (unless I'm doing something wrong)

**What is the current behavior?**
Trying to import two SASS files which contain background-image urls into a CSS file and use URL parsing to pass images to file-loader to output to build folder

**If the current behavior is a bug, please provide the steps to reproduce.**
Have a SASS file that you're importing that holds around more than 3000 css sprites (background-image: url(....)). Then send SASS files through sass-loader and css-loader

**What is the expected behavior?**
To have a generated CSS file with the correct urls thanks to file-loader and have copied all images into the build folder.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Node 6.12.3
Webpack 4.16.2
Windows 10

Below find call stack error:
`ERROR in ./XXX/src/main/sass/main.scss (./node_modules/css-loader??ref--4-1!./node_modules/sass-loader/lib/loader.js??ref--4-2!./XXX/src/main/sass/main.scss)
    Module parse failed: Maximum call stack size exceeded
    You may need an appropriate loader to handle this file type.
    RangeError: Maximum call stack size exceeded
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1425:16)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1440:10)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1440:10)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1440:10)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1440:10)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1440:10)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1440:10)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1440:10)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1440:10)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)
        at Parser.walkExpression (XXX\node_modules\webpack\lib\Parser.js:1440:10)
        at Parser.walkLeftRightExpression (XXX\node_modules\webpack\lib\Parser.js:1592:8)
        at Parser.walkBinaryExpression (XXX\node_modules\webpack\lib\Parser.js:1597:8)`

**Comment by evilebottnawi** [comment]
@Kamadake you have invalid js somewhere, webpack parser parse only js, maybe you have broken loader/plugin, not related to css-loader

**Comment by Kamadake** [comment]
I'm working with a configuration that has no JS. I am only working with SASS for testing purposes. This is another error stack that I get too:
` ERROR in ./sass/main.scss (XXX/node_modules/css-loader??ref--4-1!XXX/node_modules/sass-loader/lib/loader.js??ref--4-2!./sass/main.scss)
    Module parse failed: Maximum call stack size exceeded
    You may need an appropriate loader to handle this file type.
    RangeError: Maximum call stack size exceeded
        at RegExp.exec (native)
        at RegExp.test (native)
        at Parser.pp.canInsertSemicolon (XXX\node_modules\acorn\dist\acorn.js:609:15)
        at Parser.pp$3.parseExprAtom (XXX\node_modules\acorn\dist\acorn.js:2134:29)
        at Parser.parseExprAtom (XXX\node_modules\acorn-dynamic-import\lib\inject.js:60:31)
        at Parser.pp$3.parseExprSubscripts (XXX\node_modules\acorn\dist\acorn.js:2047:19)
        at Parser.pp$3.parseMaybeUnary (XXX\node_modules\acorn\dist\acorn.js:2024:17)
        at Parser.pp$3.parseExprOps (XXX\node_modules\acorn\dist\acorn.js:1966:19)
        at Parser.pp$3.parseMaybeConditional (XXX\node_modules\acorn\dist\acorn.js:1949:19)
        at Parser.pp$3.parseMaybeAssign (XXX\node_modules\acorn\dist\acorn.js:1925:19)
        at Parser.pp$3.parseExprList (XXX\node_modules\acorn\dist\acorn.js:2662:20)
        at Parser.pp$3.parseSubscripts (XXX\node_modules\acorn\dist\acorn.js:2075:29)
        at Parser.pp$3.parseExprSubscripts (XXX\node_modules\acorn\dist\acorn.js:2050:21)
        at Parser.pp$3.parseMaybeUnary (XXX\node_modules\acorn\dist\acorn.js:2024:17)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1985:41)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)
        at Parser.pp$3.parseExprOp (XXX\node_modules\acorn\dist\acorn.js:1987:19)`

You can see from the first line that it has converted the code from SASS to CSS and then css-loader is at a point where it's parsing the URLs.

**Comment by evilebottnawi** [comment]
@Kamadake look on stack trace - `node_modules\acorn`, `acont` it is JS parser

**Comment by evilebottnawi** [comment]
We don't use `acorn` in `css-loader`

**Comment by Kamadake** [comment]
so i have to take this with webpack then? cause it's passing through loaderRunner then to parser then to acorn

**Comment by evilebottnawi** [comment]
@Kamadake you have invalid configuration and/or broken loader/plugin
