### ISSUE TITLE
Cannot find module 'loader-utils' even though it is already installed.

### ISSUE THREAD

**Issue by gfcf14** [webpack-contrib/css-loader#910]
I am using razzle with yarn PlugNPlay for my project, and after `yarn install` I had to add/modify some packages and configuration in my `razzle.config.js`:

```
const PnpWebpackPlugin = require(`pnp-webpack-plugin`);

module.exports = {
  modify(baseConfig, { target, dev }, webpack) {
    const appConfig = Object.assign({}, baseConfig);

    appConfig.module.rules.push({
      resolve: {
        plugins: [
          PnpWebpackPlugin,
        ],
      },
    });

    return appConfig;
  },
  plugins: [
    {
      name: 'scss',
      options: {
        postcss: {
          dev: {
            sourceMap: false,
          },
        },
      },
    }
  ],
};
```
Still, I tried running my project and I get the following errors:

```
ERROR in ./src/app/app.scss (/home/gfcf14/.cache/yarn/v4/npm-css-loader-1.0.0-9f46aaa5ca41dbe31860e3b62b8e23c42916bf56/node_modules/css-loader??ref--11-1!/home/gfcf14/.cache/yarn/v4/npm-resolve-url-loader-2.3.2-83bb9ebc392b66c563795eef22f078970357a26e/node_modules/resolve-url-loader??ref--11-2!/home/gfcf14/.cache/yarn/v4/npm-postcss-loader-3.0.0-6b97943e47c72d845fa9e03f273773d4e8dd6c2d/node_modules/postcss-loader/src??ref--11-3!/home/gfcf14/.cache/yarn/v4/npm-sass-loader-7.1.0-16fd5138cb8b424bf8a759528a1972d72aad069d/node_modules/sass-loader/lib/loader.js??ref--11-4!./src/app/app.scss)
Module build failed (from /home/gfcf14/.cache/yarn/v4/npm-css-loader-1.0.0-9f46aaa5ca41dbe31860e3b62b8e23c42916bf56/node_modules/css-loader/index.js):
Error: Cannot find module 'loader-utils'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._resolveFilename (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15882:44)
    at callNativeResolution (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15487:19)
    at Object.resolveToUnqualified (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15604:22)
    at Object.resolveRequest (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15734:31)
    at Function.Module._resolveFilename (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15916:30)
    at Function.Module._load (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15832:31)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/gfcf14/.cache/yarn/v4/npm-css-loader-1.0.0-9f46aaa5ca41dbe31860e3b62b8e23c42916bf56/node_modules/css-loader/lib/loader.js:5:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Function.Module._load (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15859:14)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
 @ ./src/app/app.scss 2:14-604 21:1-42:3 22:19-609
 @ ./src/app/app.jsx
 @ ./src/client.js
 @ multi /home/gfcf14/.cache/yarn/v4/npm-razzle-dev-utils-3.0.0-alpha.2-f01885e7bc17be207c59fecbb81b27491810c925/node_modules/razzle-dev-utils/webpackHotDevClient.js ./src/client

ERROR in ./src/components/not-found/not-found.scss (/home/gfcf14/.cache/yarn/v4/npm-css-loader-1.0.0-9f46aaa5ca41dbe31860e3b62b8e23c42916bf56/node_modules/css-loader??ref--11-1!/home/gfcf14/.cache/yarn/v4/npm-resolve-url-loader-2.3.2-83bb9ebc392b66c563795eef22f078970357a26e/node_modules/resolve-url-loader??ref--11-2!/home/gfcf14/.cache/yarn/v4/npm-postcss-loader-3.0.0-6b97943e47c72d845fa9e03f273773d4e8dd6c2d/node_modules/postcss-loader/src??ref--11-3!/home/gfcf14/.cache/yarn/v4/npm-sass-loader-7.1.0-16fd5138cb8b424bf8a759528a1972d72aad069d/node_modules/sass-loader/lib/loader.js??ref--11-4!./src/components/not-found/not-found.scss)
Module build failed (from /home/gfcf14/.cache/yarn/v4/npm-css-loader-1.0.0-9f46aaa5ca41dbe31860e3b62b8e23c42916bf56/node_modules/css-loader/index.js):
Error: Cannot find module 'loader-utils'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._resolveFilename (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15882:44)
    at callNativeResolution (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15487:19)
    at Object.resolveToUnqualified (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15604:22)
    at Object.resolveRequest (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15734:31)
    at Function.Module._resolveFilename (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15916:30)
    at Function.Module._load (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15832:31)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/gfcf14/.cache/yarn/v4/npm-css-loader-1.0.0-9f46aaa5ca41dbe31860e3b62b8e23c42916bf56/node_modules/css-loader/lib/loader.js:5:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Function.Module._load (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15859:14)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
 @ ./src/components/not-found/not-found.scss 2:14-622 21:1-42:3 22:19-627
 @ ./src/components/not-found/not-found.jsx
 @ ./src/app/app.jsx
 @ ./src/client.js
✔ success server compiled in 1s 463ms

/home/gfcf14/Desktop/greendream-redesign/build/server.js:57666
!(function webpackMissingModule() { var e = new Error("Cannot find module 'razzle-dev-utils/prettyNodeErrors'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());                                            ^Error: Cannot find module 'razzle-dev-utils/prettyNodeErrors'
    at webpackMissingModule (/home/gfcf14/Desktop/greendream-redesign/build/server.js:57666:45)
    at Object.0 (/home/gfcf14/Desktop/greendream-redesign/build/server.js:57666:153)
    at __webpack_require__ (/home/gfcf14/Desktop/greendream-redesign/build/webpack:/webpack/bootstrap:682:1)
    at /home/gfcf14/Desktop/greendream-redesign/build/webpack:/webpack/bootstrap:749:1
    at Object.<anonymous> (/home/gfcf14/Desktop/greendream-redesign/build/server.js:754:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Function.Module._load (/home/gfcf14/Desktop/greendream-redesign/.pnp.js:15859:14)
    at Function.Module.runMain (module.js:693:10)
```
And this is my `package.json`:

```
{
  "name": "greendream-redesign",
  "version": "0.1.0",
  "license": "MIT",
  "installConfig": {
    "pnp": true
  },
  "scripts": {
    "start": "razzle start",
    "build": "razzle build",
    "test": "razzle test --env=jsdom",
    "start:prod": "NODE_ENV=production node build/server.js"
  },
  "dependencies": {
    "express": "^4.16.4",
    "razzle": "^3.0.0-alpha.2",
    "razzle-dev-utils": "^2.4.1",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-router-dom": "^4.3.1",
    "rebass": "^3.0.1",
    "styled-components": "^4.1.3"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-plugin-react-css-modules": "^5.2.1",
    "css-loader": "1.0.0",
    "eslint": "^5.15.3",
    "eslint-plugin-flowtype": "^3.4.2",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "loader-utils": "1.1.0",
    "pnp-webpack-plugin": "^1.4.1",
    "postcss-loader": "^3.0.0",
    "postcss-scss": "^2.0.0",
    "precss": "^4.0.0",
    "razzle-plugin-scss": "^2.4.1",
    "source-map-support": "^0.5.11",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.6"
  }
}
```
so even though `loader-utils` is installed, `css-loader` doesn't recognize it. Now, I had to downgrade my `css-loader` because of other issues (please see [this issue](https://github.com/yarnpkg/yarn/issues/7141)), would that be the problem? Or what package should I try to upgrade/downgrade to fix/circumvent this?

**Comment by evilebottnawi** [comment]
Please create issue in yarn about this, we use standard approach for dependencies. Also you don't use issue template.

**Comment by gfcf14** [comment]
@evilebottnawi is there another place related to css-loader where I could post this issue? As you can see from the post, I referenced an issue I made there, for which I am awaiting response

**Comment by arcanis** [comment]
I've just answered on https://github.com/yarnpkg/yarn/issues/7141 - I think the problem is that something is calling `realpath` on the value returned by the resolver, which causes an information loss. Now the question is what does this? The PnP plugin [disables symlink resolution](https://github.com/arcanis/pnp-webpack-plugin/blob/master/index.js#L59-L66), so something else must come into play .. maybe Razzle itself? 🤔

**Comment by evilebottnawi** [comment]
@arcanis i think problem on Razzel side, we really don't use something specify in our loader, so i don't think problem related to css-loader directly
