### ISSUE TITLE
Webpacak Upgrade from 1 to 3 is failing

### ISSUE THREAD

**Issue by hbadri1** [webpack-contrib/css-loader#912]
Hi there, I am working on upgrading my webpack to 4, but I would be better to pass through version 2 or 3 first.

Please find below my config: 

```
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');

const PATHS = {
  app: path.join(__dirname, 'src/js'),
  build: path.join(__dirname, 'build'),
  public: path.join(__dirname, 'src/public'),
  assets: path.join(__dirname, 'src/assets'),
  styles: [
    path.join(__dirname, 'src/assets/css/bootstrap.min.css'),
    path.join(__dirname, 'src/assets/css/font-awesome.min.css'),
    path.join(__dirname, 'src/assets/css/bootstrap-grid-rtl.css'),
    path.join(__dirname, 'src/assets/css/main.css'),
    path.join(__dirname, 'src/assets/css/PrintStyle.css'),
    path.join(__dirname, 'node_modules/react-dates/lib/css/_datepicker.css'),
    path.join(__dirname, 'node_modules/flag-icon-css/css/flag-icon.css'),
    path.join(__dirname, 'src/assets/css/react-datepicker.css'),
    path.join(__dirname, 'src/assets/css/tracker.css'),
    
  ]
};

const isDebug = !process.argv.includes('--release');

module.exports = {
  entry: {
    app: ['babel-polyfill', PATHS.app],
    style: PATHS.styles
  },
  output: {
    path: PATHS.build,
    filename: 'js/[name].js',
    publicPath:''
  },
  resolve: {
    extensions: ['.css', '.js', '.jsx']
  },

  module: {
    rules: [
      {
        test: /\.jsx?$/,
        use: [
          {
            loader: "babel-loader",
            options: {
              cacheDirectory: isDebug,
              babelrc: true,
              presets: [
                'latest',
                'react',
                ...isDebug ? [] : [
                  'react-optimize',
                ],
              ],
              plugins: [
                'transform-object-rest-spread',
                'transform-object-assign',
                [
                  'react-intl', {
                    'messagesDir': './build/messages',
                    'enforceDescriptions': false
                  }
                ]
              ]
            }
          }
        ],
        include: [
          path.resolve(__dirname, PATHS.app),
        ]
      },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: [
            /*{
              loader: 'resolve-url-loader',
              options: {
                isDebug: true
              }
            },*/
            {
              loader: 'css-loader',
              options: {
                importLoaders: 1,
                sourceMap: true,
                modules: true,
                localIdentName: isDebug ? '[name]-[local]-[hash:base64:5]' : '[hash:base64:5]'
              }
            },
            {
              loader: 'postcss-loader',
              options: {
                sourceMap: true
              }
            }
          ]
        }),
        exclude: PATHS.styles,
      },
      /*{
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'resolve-url-loader'
            },
            {
              loader: 'css-loader',
              options: {
                localIdentName: isDebug ? '[name]-[local]-[hash:base64:5]' : '[hash:base64:5]'
              }
            },
            
          ]
        }),
        exclude: PATHS.app,
        include: PATHS.styles
      },*/


      /*{
        test: /\.sss$/,
        use: [
          {
            loader: 'resolve-url-loader'
          },
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          }
        ]
      },*/
      {
        test: /\.json$/,
        use: [
          {
            loader: 'json-loader'
          }
        ]
      },
      {
        test: /\.(eot|otf|webp|svg|ttf|woff|woff2)(\?.*)?$/,
        use: [
          {
            loader: 'file-loader',
            options: {
               name: isDebug ? '/[path][name].[ext]?[hash:8]' : '/fonts/[hash:8].[ext]',
            }
          }
        ]
      },
      {
        test: /\.(ico|jpg|jpeg|png|gif)(\?.*)?$/,
        use: [
          {
            loader:
              `file-loader?${JSON.stringify({
                name: isDebug ? '/[path][name].[ext]?[hash:8]' : '/images/[hash:8].[ext]'
              })}`
          }
        ]
      },
    ],
  },
  plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        context: __dirname,
        postcss: [
          require('postcss-partial-import')(),
          require('postcss-url')(),
          require('postcss-custom-properties')(),
          require('postcss-custom-media')(),
          require('postcss-media-minmax')(),
          require('postcss-custom-selectors')(),
          require('autoprefixer')({
            browsers: [
              '>1%',
              'last 4 versions',
              'Firefox ESR',
              'not ie < 9', 
            ],
          })
        ]
      }
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': isDebug ? '"development"' : '"production"',
      'process.env.BROWSER': true,
      __DEV__: isDebug,
    }),
    /*new webpack.optimize.UglifyJsPlugin({
      compress: {
        properties: true
      }
      }),*/
    new ExtractTextPlugin({
      filename: '[name].css',
      allChunks: true,
      disable: false
    }),

    new OptimizeCssAssetsPlugin({
      cssProcessorOptions: {
        //discardComments: { removeAll: true }
      },
    }),
    new HtmlWebpackPlugin({
      title: 'Washaj Portal',
      template: path.join(PATHS.public, 'index.ejs'),
      favicon:  path.join(PATHS.assets, 'images/favicon.ico'),
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
    }),
    ...isDebug? [
      new webpack.HotModuleReplacementPlugin({
        multiStep: true
      }),
    ] : [
      new CleanWebpackPlugin(PATHS.build, {
        root: process.cwd()
      }),
      new webpack.optimize.OccurrenceOrderPlugin(true),
      new webpack.optimize.DedupePlugin()
    ]
],

bail: !isDebug,
cache: false,

stats: {
  colors: true,
  reasons: isDebug,
  timings: true,
},

devtool: isDebug ? 'cheap-module-source-map' : false,
devServer: {
  historyApiFallback: true,
  hot: true,
  inline: true,
  stats: 'errors-only',
  port: 3000,
  host: '0.0.0.0',
  publicPath: '/',
  contentBase: PATHS.build,
  proxy: {
    '/api/**': {
      target: 'http://localhost:8080',
      secure: false
    }
  }
}
};
```

And here some output of the inspection: 

```
  ERROR in ./node_modules/css-loader/dist/cjs.js??ref--1-2!./node_modules/postcss-loader??ref--1-3!./src/js/components/Home/Home.css
    Module build failed: TypeError: Path must be a string. Received undefined
        at C:\Users\badri\Desktop\WORK\WASHAJ\washaj\gaca-frontend\src\js\components\Home\Home.css:1:1
        at assertPath (path.js:28:11)
        at Object.relative (path.js:558:5)
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

You have old version of webpack, maybe you use this locally

**Comment by evilebottnawi** [comment]
Remove `webpack.LoaderOptionsPlugin` and put all options to loader, this plugin doesn't need for webpack@4

**Comment by hbadri1** [comment]
@evilebottnawi dear I'm upgrading to 3 not to 1. So, I'm still in need for `webpack.LoaderOptionsPlugin`. Sorry but I didn't understand what template should I follow.
